### ISSUE TITLE
Update to 6.2.4 version

### ISSUE THREAD

**Issue by kolobok1386** [AppsFlyerSDK/appsflyer-unreal-plugin#12]
Could you update UE4 plugin with Appsflyer 6.2.4 version.

**Comment by GM-appsflyer** [comment]
Hey @kolobok1386 ,
We'll release an update today.

**Comment by kolobok1386** [comment]
Hi @GM-appsflyer ,

Great news! Can see pull request with SDK update, but it still not merged, when do you plan to merge this update? 
thanks :)
