### ISSUE TITLE
No events logged

### ISSUE THREAD

**Issue by FunnyCOFE** [AppsFlyerSDK/appsflyer-unreal-plugin#28]
# Report

## What did you do?

I installed and enabled plugin. Added info in Project Settings. Automatic start the AppsFlyer SDK enabled. Is Debug disabled.  Added some Nodes "AppsFlyerSDK log event via Blueprint Map Node with Map Node".
![image](https://user-images.githubusercontent.com/18552584/180849058-e5804f43-0041-47e3-9e70-9509a2822e20.png)
Uploaded to Internal Test on Google Play, but no events in dashboard shown...

## What did you expect to happen?

Event to be logged

## What happened instead?

No events logged

## SDK Version

I dont know

## Plugin Version

6.1.4

## On what Platform are you having the issue?

Android

**Comment by FunnyCOFE** [comment]
Same on iOS

**Comment by FunnyCOFE** [comment]
In Editor LogEvent raised 
![image](https://user-images.githubusercontent.com/18552584/180995482-6c1949fe-b0a0-407e-80e4-fb93e245cc73.png)

**Comment by andr-ggn** [comment]
Our SDK works with iOS/Android devices
