### ISSUE TITLE
Unreal 5.2.1 Packaging Error

### ISSUE THREAD

**Issue by tuomaskarmakallio** [AppsFlyerSDK/appsflyer-unreal-plugin#33]
# Report

## What did you do?

Packaging for Android on Unreal 5.2.1

## What did you expect to happen?

Packaging completes successfully

## What happened instead?

Error:

UATHelper: Packaging (Android (ASTC)): [1/3] Compile [arm64] UE4AFSDKDelegate.mm
UATHelper: Packaging (Android (ASTC)): error: Objective-C was disabled in PCH file but is currently enabled
UATHelper: Packaging (Android (ASTC)): 1 error generated.
PackagingResults: Error: Objective-C was disabled in PCH file but is currently enabled

## SDK Version

Not sure where that can be found.

## Plugin Version

"VersionName": "6.10.1",

## On what Platform are you having the issue?

Packaging for Android on both Win64 and MacOS

**Comment by andr-ggn** [comment]
Are you sure that is related to AppsFlyer Plugin?

**Comment by tuomaskarmakallio** [comment]
Yes : we solved it like this:
* Created a folder called IOS
* moving E4AFSDKDelegate.h and .mm files into that folder
* updating the line to #import "IOS/UE4AFSDKDelegate.h"

**Comment by andr-ggn** [comment]
Many thanks @tuomaskarmakallio!

https://github.com/AppsFlyerSDK/appsflyer-unreal-plugin/releases/tag/v6.12.2
