### ISSUE TITLE
Android build :app:assembleRelease failed

### ISSUE THREAD

**Issue by GloryOfNight** [AppsFlyerSDK/appsflyer-unreal-plugin#6]
# Report

## What did you do?
Applied plugin to project based on Unreal Engine 4.21.2.
Launched project and started build Android -> Android ETC1

## What did you expect to happen?
Build success

## What happened instead?
Build failed with  :app:assembleRelease
Also log shown these warnings:

Warning: com.appsflyer.FirebaseInstanceIdListener: can't find superclass or interface com.google.firebase.iid.FirebaseInstanceIdService
Warning: com.appsflyer.FirebaseInstanceIdListener: can't find referenced class com.google.firebase.iid.FirebaseInstanceId
Warning: com.appsflyer.FirebaseInstanceIdListener: can't find referenced class com.google.firebase.iid.FirebaseInstanceIdService
Warning: com.appsflyer.FirebaseInstanceIdListener: can't find referenced class com.google.firebase.iid.FirebaseInstanceId
Warning: com.appsflyer.FirebaseInstanceIdListener: can't find referenced class com.google.firebase.iid.FirebaseInstanceId
Warning: com.appsflyer.FirebaseInstanceIdListener: can't find referenced class com.google.firebase.iid.FirebaseInstanceIdService
Warning: com.appsflyer.FirebaseInstanceIdListener: can't find referenced class com.google.firebase.iid.FirebaseInstanceIdService
Warning: com.appsflyer.y: can't find referenced class com.google.firebase.iid.FirebaseInstanceIdService

## SDK Version
v4.9.0

## Plugin Version
v1.0

## On what Platform are you having the issue?
Android

**Comment by GloryOfNight** [comment]
Fixed issue for me with applying:

>   implementation 'com.google.firebase:firebase-core:11.8.0'

to
  
> 
> > AppsFlyer_UPL.xml
> 
>           dependencies {
>           implementation 'com.android.installreferrer:installreferrer:1.0'
>           implementation 'com.appsflyer:af-android-sdk:4.9.0'
>           implementation 'com.google.firebase:firebase-core:11.8.0' // applied line
>           }

**Comment by xford450** [comment]
I've tried your fix but the log now shows me SQLite error (Can't find common super class of [android/database/sqlite/SQLiteDatabase]). Do you have any idea how to fix this?

**Comment by GloryOfNight** [comment]
@xford450, i forked this git and upload my changes. You can check it.
4.23 for me android work fine, ios not sure. 

https://github.com/GloryOfNight/unreal_appsflyer_sdk

**Comment by xford450** [comment]
> @xford450, i forked this git and upload my changes. You can check it.
> 4.23 for android work fine, ios not sure.
> 
> https://github.com/GloryOfNight/unreal_appsflyer_sdk

I've tried your fixed plugin files but the same error appeared again. Have you tested shipping build? I have no problem to package app in development build.

**Comment by GloryOfNight** [comment]
Yep. Work fine for me with signed shipping build.
